package com.guinea.datadb.mysql.entity;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import java.io.Serializable;

/****
 * 账户详情
 * @author shiky
 *
 */
public class SysAccountDetail implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.id
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.uid
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.weixin
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.address
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.nationality
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.age
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private Short age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.createBro
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String createbro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.createBroVersion
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String createbroversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.careateSystem
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String careatesystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.sfID
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String sfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.city
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.mlike
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String mlike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.skype
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String skype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.feixin
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String feixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_detail.qq
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    private String qq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.id
     *
     * @return the value of sys_account_detail.id
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.id
     *
     * @param id the value for sys_account_detail.id
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.uid
     *
     * @return the value of sys_account_detail.uid
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.uid
     *
     * @param uid the value for sys_account_detail.uid
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.weixin
     *
     * @return the value of sys_account_detail.weixin
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.weixin
     *
     * @param weixin the value for sys_account_detail.weixin
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.address
     *
     * @return the value of sys_account_detail.address
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.address
     *
     * @param address the value for sys_account_detail.address
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.nationality
     *
     * @return the value of sys_account_detail.nationality
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.nationality
     *
     * @param nationality the value for sys_account_detail.nationality
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.age
     *
     * @return the value of sys_account_detail.age
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.age
     *
     * @param age the value for sys_account_detail.age
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.createBro
     *
     * @return the value of sys_account_detail.createBro
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getCreatebro() {
        return createbro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.createBro
     *
     * @param createbro the value for sys_account_detail.createBro
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setCreatebro(String createbro) {
        this.createbro = createbro == null ? null : createbro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.createBroVersion
     *
     * @return the value of sys_account_detail.createBroVersion
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getCreatebroversion() {
        return createbroversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.createBroVersion
     *
     * @param createbroversion the value for sys_account_detail.createBroVersion
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setCreatebroversion(String createbroversion) {
        this.createbroversion = createbroversion == null ? null : createbroversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.careateSystem
     *
     * @return the value of sys_account_detail.careateSystem
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getCareatesystem() {
        return careatesystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.careateSystem
     *
     * @param careatesystem the value for sys_account_detail.careateSystem
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setCareatesystem(String careatesystem) {
        this.careatesystem = careatesystem == null ? null : careatesystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.sfID
     *
     * @return the value of sys_account_detail.sfID
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getSfid() {
        return sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.sfID
     *
     * @param sfid the value for sys_account_detail.sfID
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setSfid(String sfid) {
        this.sfid = sfid == null ? null : sfid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.city
     *
     * @return the value of sys_account_detail.city
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.city
     *
     * @param city the value for sys_account_detail.city
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.mlike
     *
     * @return the value of sys_account_detail.mlike
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getMlike() {
        return mlike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.mlike
     *
     * @param mlike the value for sys_account_detail.mlike
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setMlike(String mlike) {
        this.mlike = mlike == null ? null : mlike.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.skype
     *
     * @return the value of sys_account_detail.skype
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getSkype() {
        return skype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.skype
     *
     * @param skype the value for sys_account_detail.skype
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setSkype(String skype) {
        this.skype = skype == null ? null : skype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.feixin
     *
     * @return the value of sys_account_detail.feixin
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getFeixin() {
        return feixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.feixin
     *
     * @param feixin the value for sys_account_detail.feixin
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setFeixin(String feixin) {
        this.feixin = feixin == null ? null : feixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_detail.qq
     *
     * @return the value of sys_account_detail.qq
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_detail.qq
     *
     * @param qq the value for sys_account_detail.qq
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}