package com.guinea.datadb.mysql.entity;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import java.io.Serializable;

/***
 * 用户角色
 * @author shiky
 *
 */
public class UserRole implements Serializable{

    private static final long serialVersionUID = -404638695680058481L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.u_id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.r_id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    private Long rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.id
     *
     * @return the value of user_role.id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.id
     *
     * @param id the value for user_role.id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.u_id
     *
     * @return the value of user_role.u_id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.u_id
     *
     * @param uId the value for user_role.u_id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.r_id
     *
     * @return the value of user_role.r_id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.r_id
     *
     * @param rId the value for user_role.r_id
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}