package com.guinea.datadb.mysql.entity.card;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.math.BigDecimal;

/***
 * 刷刷商户
 */
public class CardMerchant implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_merchant.id
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_merchant.operator_id
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_merchant.code
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_merchant.rate
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    private Float rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_merchant.name
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    private String name;

    /***
     * 运营商名称
     */
    private String operator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_merchant.id
     *
     * @return the value of fund_card_merchant.id
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_merchant.id
     *
     * @param id the value for fund_card_merchant.id
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_merchant.operator_id
     *
     * @return the value of fund_card_merchant.operator_id
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_merchant.operator_id
     *
     * @param operatorId the value for fund_card_merchant.operator_id
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    public Long getCode() {
        return code;
    }

    public Float getRate() {
        return rate;
    }

    public void setCode(Long code) {
        this.code = code;
    }

    public void setRate(Float rate) {
        this.rate = rate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_merchant.name
     *
     * @return the value of fund_card_merchant.name
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_merchant.name
     *
     * @param name the value for fund_card_merchant.name
     *
     * @mbggenerated Fri May 20 10:52:35 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getOperator_name() {
        return operator_name;
    }

    public void setOperator_name(String operator_name) {
        this.operator_name = operator_name;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}