package com.guinea.datadb.mysql.entity.card;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/***
 * 刷刷结算
 */
public class CardTransactratePayment implements Serializable{

    private static final long serialVersionUID = 4048166286259467747L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.merchant_id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.user_id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.total_transactrate_money
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private BigDecimal totalTransactrateMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.total_cash_payment
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private BigDecimal totalCashPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.transactrate_count
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private Short transactrateCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.transactrate_date
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private Date transactrateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.wish_payment_time
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private Date wishPaymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_card_transactrate_payment.ps
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    private String ps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.id
     *
     * @return the value of fund_card_transactrate_payment.id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.id
     *
     * @param id the value for fund_card_transactrate_payment.id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.merchant_id
     *
     * @return the value of fund_card_transactrate_payment.merchant_id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.merchant_id
     *
     * @param merchantId the value for fund_card_transactrate_payment.merchant_id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.user_id
     *
     * @return the value of fund_card_transactrate_payment.user_id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.user_id
     *
     * @param userId the value for fund_card_transactrate_payment.user_id
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.total_transactrate_money
     *
     * @return the value of fund_card_transactrate_payment.total_transactrate_money
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public BigDecimal getTotalTransactrateMoney() {
        return totalTransactrateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.total_transactrate_money
     *
     * @param totalTransactrateMoney the value for fund_card_transactrate_payment.total_transactrate_money
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setTotalTransactrateMoney(BigDecimal totalTransactrateMoney) {
        this.totalTransactrateMoney = totalTransactrateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.total_cash_payment
     *
     * @return the value of fund_card_transactrate_payment.total_cash_payment
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public BigDecimal getTotalCashPayment() {
        return totalCashPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.total_cash_payment
     *
     * @param totalCashPayment the value for fund_card_transactrate_payment.total_cash_payment
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setTotalCashPayment(BigDecimal totalCashPayment) {
        this.totalCashPayment = totalCashPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.transactrate_count
     *
     * @return the value of fund_card_transactrate_payment.transactrate_count
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public Short getTransactrateCount() {
        return transactrateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.transactrate_count
     *
     * @param transactrateCount the value for fund_card_transactrate_payment.transactrate_count
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setTransactrateCount(Short transactrateCount) {
        this.transactrateCount = transactrateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.transactrate_date
     *
     * @return the value of fund_card_transactrate_payment.transactrate_date
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public Date getTransactrateDate() {
        return transactrateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.transactrate_date
     *
     * @param transactrateDate the value for fund_card_transactrate_payment.transactrate_date
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setTransactrateDate(Date transactrateDate) {
        this.transactrateDate = transactrateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.wish_payment_time
     *
     * @return the value of fund_card_transactrate_payment.wish_payment_time
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public Date getWishPaymentTime() {
        return wishPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.wish_payment_time
     *
     * @param wishPaymentTime the value for fund_card_transactrate_payment.wish_payment_time
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setWishPaymentTime(Date wishPaymentTime) {
        this.wishPaymentTime = wishPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_card_transactrate_payment.ps
     *
     * @return the value of fund_card_transactrate_payment.ps
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public String getPs() {
        return ps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_card_transactrate_payment.ps
     *
     * @param ps the value for fund_card_transactrate_payment.ps
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    public void setPs(String ps) {
        this.ps = ps == null ? null : ps.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}