package com.guinea.datadb.mysql.persistence.card;

import com.guinea.datadb.mysql.entity.card.CardTransactrateInfo;
import java.util.List;
import java.util.Map;

public interface CardTransactrateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_info
     *
     * @mbggenerated Sat Jun 18 13:50:08 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_info
     *
     * @mbggenerated Sat Jun 18 13:50:08 CST 2016
     */
    int insert(CardTransactrateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_info
     *
     * @mbggenerated Sat Jun 18 13:50:08 CST 2016
     */
    CardTransactrateInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_info
     *
     * @mbggenerated Sat Jun 18 13:50:08 CST 2016
     */
    List<CardTransactrateInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_info
     *
     * @mbggenerated Sat Jun 18 13:50:08 CST 2016
     */
    int updateByPrimaryKey(CardTransactrateInfo record);

    /***
     * page
     * @param conditions
     * @return
     */
    List<CardTransactrateInfo> findByPage(Map<String,String> conditions);

    /***
     * 结算日内的交易查询(t-1日)
     * @param conditions
     * @return
     */
    List<CardTransactrateInfo> selectByPaymentTime(Map<String,String> conditions);
}