package com.guinea.datadb.mysql.persistence.card;

import com.guinea.datadb.mysql.entity.card.CardOperator;
import java.util.List;
import java.util.Map;

public interface CardOperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_operator
     *
     * @mbggenerated Fri May 20 10:46:42 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_operator
     *
     * @mbggenerated Fri May 20 10:46:42 CST 2016
     */
    int insert(CardOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_operator
     *
     * @mbggenerated Fri May 20 10:46:42 CST 2016
     */
    CardOperator selectByPrimaryKey(Long id);

    /***
     * 查询通过名称
     * @param name
     * @return
     */
    CardOperator selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_operator
     *
     * @mbggenerated Fri May 20 10:46:42 CST 2016
     */
    List<CardOperator> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_operator
     *
     * @mbggenerated Fri May 20 10:46:42 CST 2016
     */
    int updateByPrimaryKey(CardOperator record);

    /***
     * page分页查询
     * @param conditions
     * @return
     */
    List<CardOperator> findByPage(Map<String,String> conditions);
}