package com.guinea.datadb.mysql.persistence.card;

import com.guinea.datadb.mysql.entity.card.CardTransactratePayment;
import java.util.List;

public interface CardTransactratePaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_payment
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_payment
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    int insert(CardTransactratePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_payment
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    CardTransactratePayment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_payment
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    List<CardTransactratePayment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_card_transactrate_payment
     *
     * @mbggenerated Wed Jun 22 10:09:08 CST 2016
     */
    int updateByPrimaryKey(CardTransactratePayment record);
}