package com.guinea.datadb.mysql.entity;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.math.BigDecimal;

/***
 * 位置点
 * @author shiky
 *
 */
public class TracePoint implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5618708810607246413L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_point.id
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_point.pName
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_point.address
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_point.lgt
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    private BigDecimal lgt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_point.lat
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    private BigDecimal lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_point.scope
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    private Float scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace_point.uid
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_point.id
     *
     * @return the value of trace_point.id
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_point.id
     *
     * @param id the value for trace_point.id
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_point.pName
     *
     * @return the value of trace_point.pName
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_point.pName
     *
     * @param pname the value for trace_point.pName
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_point.address
     *
     * @return the value of trace_point.address
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_point.address
     *
     * @param address the value for trace_point.address
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_point.lgt
     *
     * @return the value of trace_point.lgt
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public BigDecimal getLgt() {
        return lgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_point.lgt
     *
     * @param lgt the value for trace_point.lgt
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public void setLgt(BigDecimal lgt) {
        this.lgt = lgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_point.lat
     *
     * @return the value of trace_point.lat
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_point.lat
     *
     * @param lat the value for trace_point.lat
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_point.scope
     *
     * @return the value of trace_point.scope
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public Float getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_point.scope
     *
     * @param scope the value for trace_point.scope
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public void setScope(Float scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace_point.uid
     *
     * @return the value of trace_point.uid
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace_point.uid
     *
     * @param uid the value for trace_point.uid
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}