package com.guinea.datadb.mysql.entity;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

/****
 * 股票
 * 
 * @author shiky
 *
 */
public class FundStock {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fund_stock.id
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fund_stock.sCode
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	private String scode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fund_stock.sName
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	private String sname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fund_stock.sType
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	private Short stype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fund_stock.sPace
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	private Short space;

	private String stypeName, spaceName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fund_stock.id
	 *
	 * @return the value of fund_stock.id
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fund_stock.id
	 *
	 * @param id
	 *            the value for fund_stock.id
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fund_stock.sCode
	 *
	 * @return the value of fund_stock.sCode
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public String getScode() {
		return scode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fund_stock.sCode
	 *
	 * @param scode
	 *            the value for fund_stock.sCode
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public void setScode(String scode) {
		this.scode = scode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fund_stock.sName
	 *
	 * @return the value of fund_stock.sName
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fund_stock.sName
	 *
	 * @param sname
	 *            the value for fund_stock.sName
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public void setSname(String sname) {
		this.sname = sname == null ? null : sname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fund_stock.sType
	 *
	 * @return the value of fund_stock.sType
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public Short getStype() {
		return stype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fund_stock.sType
	 *
	 * @param stype
	 *            the value for fund_stock.sType
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public void setStype(Short stype) {
		this.stype = stype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fund_stock.sPace
	 *
	 * @return the value of fund_stock.sPace
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public Short getSpace() {
		return space;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fund_stock.sPace
	 *
	 * @param space
	 *            the value for fund_stock.sPace
	 *
	 * @mbggenerated Thu Sep 17 09:19:57 CST 2015
	 */
	public void setSpace(Short space) {
		this.space = space;
	}

	public String getSpaceName() {
		return spaceName;
	}

	public String getStypeName() {
		return stypeName;
	}

	public void setStypeName(String stypeName) {
		this.stypeName = stypeName;
	}

	public void setSpaceName(String spaceName) {
		this.spaceName = spaceName;
	}

	public String toString() {
		return ReflectionToStringBuilder.toString(this);
	}
}