package com.guinea.datadb.mysql.entity;

import java.io.Serializable;

/***
 * shiky
 */
public class SysOrganization implements Serializable{

    private static final long serialVersionUID = 983377304856445807L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.id
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.parent_id
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.org_name
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.description
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.available
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    private Short available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.id
     *
     * @return the value of sys_organization.id
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.id
     *
     * @param id the value for sys_organization.id
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.parent_id
     *
     * @return the value of sys_organization.parent_id
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.parent_id
     *
     * @param parentId the value for sys_organization.parent_id
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.org_name
     *
     * @return the value of sys_organization.org_name
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.org_name
     *
     * @param orgName the value for sys_organization.org_name
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.description
     *
     * @return the value of sys_organization.description
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.description
     *
     * @param description the value for sys_organization.description
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.available
     *
     * @return the value of sys_organization.available
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public Short getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.available
     *
     * @param available the value for sys_organization.available
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    public void setAvailable(Short available) {
        this.available = available;
    }
}