package com.guinea.datadb.mysql.persistence.dic;

import com.guinea.datadb.mysql.entity.dic.VacationCalendar;
import java.util.List;

public interface VacationCalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_vacation_calendar
     *
     * @mbggenerated Wed Jun 01 15:39:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_vacation_calendar
     *
     * @mbggenerated Wed Jun 01 15:39:46 CST 2016
     */
    int insert(VacationCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_vacation_calendar
     *
     * @mbggenerated Wed Jun 01 15:39:46 CST 2016
     */
    VacationCalendar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_vacation_calendar
     *
     * @mbggenerated Wed Jun 01 15:39:46 CST 2016
     */
    List<VacationCalendar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_vacation_calendar
     *
     * @mbggenerated Wed Jun 01 15:39:46 CST 2016
     */
    int updateByPrimaryKey(VacationCalendar record);
}