package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.FundStock;
import java.util.List;
import java.util.Map;

public interface FundStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_stock
     *
     * @mbggenerated Wed Dec 09 16:30:19 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_stock
     *
     * @mbggenerated Wed Dec 09 16:30:19 CST 2015
     */
    int insert(FundStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_stock
     *
     * @mbggenerated Wed Dec 09 16:30:19 CST 2015
     */
    FundStock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_stock
     *
     * @mbggenerated Wed Dec 09 16:30:19 CST 2015
     */
    List<FundStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_stock
     *
     * @mbggenerated Wed Dec 09 16:30:19 CST 2015
     */
    int updateByPrimaryKey(FundStock record);

    /***
     *
     * @param sCode
     * @return
     */
    List<FundStock> selectByCode(String sCode);

    /***
     * page
     * @param conditions
     * @return
     */
    List<FundStock> findByPage(Map<String,String> conditions);
}