package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.FundTransactrate;
import java.util.List;
import java.util.Map;

public interface FundTransactrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_transactrate
     *
     * @mbggenerated Wed Dec 09 16:31:53 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_transactrate
     *
     * @mbggenerated Wed Dec 09 16:31:53 CST 2015
     */
    int insert(FundTransactrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_transactrate
     *
     * @mbggenerated Wed Dec 09 16:31:53 CST 2015
     */
    FundTransactrate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_transactrate
     *
     * @mbggenerated Wed Dec 09 16:31:53 CST 2015
     */
    List<FundTransactrate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_transactrate
     *
     * @mbggenerated Wed Dec 09 16:31:53 CST 2015
     */
    int updateByPrimaryKey(FundTransactrate record);

    /***
     * page
     * @param conditions
     * @return
     */
    List<FundTransactrate> findByPage(Map<String,String> conditions);
}