package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.RoleResource;

import java.util.List;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Tue Jan 05 15:38:34 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /***
     * 删除通过角色id
     *
     * @param roleId
     * @return
     */
    int deleteByRoleId(Long roleId);

    /***
     * 删除通过资源id
     *
     * @param resourceId
     * @return
     */
    int deleteByResourceId(Long resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Tue Jan 05 15:38:34 CST 2016
     */
    int insert(RoleResource record);

    /***
     * 批量插入
     *
     * @param roleResources
     * @return
     */
    int bathInsert(List<RoleResource> roleResources);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Tue Jan 05 15:38:34 CST 2016
     */
    RoleResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Tue Jan 05 15:38:34 CST 2016
     */
    List<RoleResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Tue Jan 05 15:38:34 CST 2016
     */
    int updateByPrimaryKey(RoleResource record);

    /***
     * 通过资源id
     *
     * @param resourceId
     * @return
     */
    List<RoleResource> selectByResourceId(Long resourceId);

    /***
     * 通过角色id
     *
     * @param roleId
     * @return
     */
    List<RoleResource> selectByRoleId(Long roleId);
}