package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.SysAccountDetail;
import java.util.List;

public interface SysAccountDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_detail
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_detail
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    int insert(SysAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_detail
     * 查询通过id
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    SysAccountDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_detail
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    List<SysAccountDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_detail
     *
     * @mbggenerated Tue Dec 08 16:02:12 CST 2015
     */
    int updateByPrimaryKey(SysAccountDetail record);

    /***
     *
     * @param record
     * @return
     */
    List<SysAccountDetail> selectByObj(SysAccountDetail record);
}