package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.SysResource;
import java.util.List;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Dec 28 14:29:50 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Dec 28 14:29:50 CST 2015
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Dec 28 14:29:50 CST 2015
     */
    SysResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Dec 28 14:29:50 CST 2015
     */
    List<SysResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Dec 28 14:29:50 CST 2015
     */
    int updateByPrimaryKey(SysResource record);

    /***
     * 同一父节点下名称不能重复
     * @param record
     * @return
     */
    List<SysResource> selectByNameForPId(SysResource record);
}