package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.SysRole;
import com.guinea.datadb.mysql.model.RoleRangeView;

import java.util.List;
import java.util.Map;

/***
 * 角色
 */
public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Dec 31 08:37:16 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Dec 31 08:37:16 CST 2015
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Dec 31 08:37:16 CST 2015
     */
    SysRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Dec 31 08:37:16 CST 2015
     */
    List<SysRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Dec 31 08:37:16 CST 2015
     */
    int updateByPrimaryKey(SysRole record);

    //查询通过name
    List<SysRole> selectByName(String name);

    //分页查询
    List<SysRole> findByPage(Map<String, String> conditions);

    /***
     * 用户角色权限
     * @return
     */
    List<RoleRangeView> selectByRoleRange();
}