package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.UserOrganization;
import com.guinea.datadb.mysql.model.UserOrganizationView;

import java.util.List;

public interface UserOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Fri Jan 08 13:08:47 CST 2016
     */
    int deleteByPrimaryKey(Long id);


    /***
     * 删除通过用户id
     *
     * @param id
     * @return
     */
    int deleteByUserId(Long id);

    /***
     * 删除通过组织id
     *
     * @param id
     * @return
     */
    int deleteByOrgId(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Fri Jan 08 13:08:47 CST 2016
     */
    int insert(UserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Fri Jan 08 13:08:47 CST 2016
     */
    UserOrganization selectByPrimaryKey(Long id);

    /****
     * 查询通过用户id
     *
     * @param userId
     * @return
     */
    List<UserOrganization> selectByUserId(Long userId);

    /***
     * 查询通过组织id
     *
     * @param userId
     * @return
     */
    List<UserOrganization> selectByOrgId(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Fri Jan 08 13:08:47 CST 2016
     */
    List<UserOrganization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organization
     *
     * @mbggenerated Fri Jan 08 13:08:47 CST 2016
     */
    int updateByPrimaryKey(UserOrganization record);

    /***
     * @return
     */
    List<UserOrganizationView> selectUserOrgIdAll();
}