package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.SysOrganization;

import java.util.List;

public interface SysOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    int insert(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    SysOrganization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    List<SysOrganization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Fri Jan 08 13:20:22 CST 2016
     */
    int updateByPrimaryKey(SysOrganization record);

    /***
     * 查询通过父id,和名称
     * @param record
     * @return
     */
    List<SysOrganization> selectByNameForPId(SysOrganization record);
}