package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.TracePoint;
import java.util.List;
import java.util.Map;

public interface TracePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_point
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_point
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    int insert(TracePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_point
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    TracePoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_point
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    List<TracePoint> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace_point
     *
     * @mbggenerated Thu Dec 17 15:57:00 CST 2015
     */
    int updateByPrimaryKey(TracePoint record);

    /****
     *
     * @param conditions
     * @return
     */
    List<TracePoint> findByPage(Map<String,String> conditions);
}