package com.guinea.datadb.mysql.persistence;

import com.guinea.datadb.mysql.entity.UserRole;

import java.util.List;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /***
     * 删除通过角色id
     *
     * @param roleId
     * @return
     */
    int deleteByRoleId(Long roleId);

    /****
     * 删除通过用户id
     *
     * @param userId
     * @return
     */
    int deleteByUserId(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    int insert(UserRole record);

    /***
     * 批量插入
     *
     * @param userRoles
     * @return
     */
    int bathInsert(List<UserRole> userRoles);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    UserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    List<UserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 15 16:22:56 CST 2015
     */
    int updateByPrimaryKey(UserRole record);

    /***
     * 查询通过角色id
     * @param rid
     * @return
     */
    List<UserRole> selectByRoleId(Long rid);

    /***
     * 查询通过用户id
     * @param uid
     * @return
     */
    List<UserRole> selectByUserId(Long uid);
}